---
abstract: 'Optional PDF::API2 add-on using XS to speed up expensive operations'
author:
  - 'Rob Scovell <robscovell@48hc.com>'
build_requires:
  PDF::API2: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: PDF-API2-XS
requires:
  perl: v5.10.0
resources:
  repository: git://github.com/ssimms/pdfapi2xs.git
version: '1.002'
x_generated_by_perl: v5.28.1
x_serialization_backend: 'YAML::Tiny version 1.73'
